image: golang:1.7-alpine

stages:
  - install-environment
  - build
  - test

install-go:
  stage: install-environment
  script:
    - go version
    - echo $PATH
    - go env
    - which go

build-my-project:
  stage: build
  script:
    - go build

test-my-project:
  stage: test
  script:
    - go test

before_script:
  - apk update && apk add git
  - go get github.com/spf13/cobra
  - go get github.com/spf13/viper
