image: golang:1.7-alpine

stages:
  - check-environment
  - test
  - build

check-go:
  stage: check-environment
  script:
    - go version
    - echo $PATH
    - go env
    - which go

build_linux:
  stage: build
  script:
    - go build -o FileSwitcher
  artifacts:
    paths:
      - FileSwitcher

build_win32:
  stage: build
  script:
    - GOOS=windows GOARCH=386 go build -o FileSwitcher.exe
  artifacts:
    paths:
      - FileSwitcher.exe

build_macos:
  stage: build
  script:
    - GOOS=darwin GOARCH=amd64 go build -o FileSwitcher
  artifacts:
    paths:
      - FileSwitcher

test:
  stage: test
  script:
    - go test

before_script:
  - apk update && apk add git
  - go get github.com/spf13/cobra
  - go get github.com/spf13/viper
